name: Trigger Cloudflare Pages Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Cloudflare Pages Webhook
        run: curl -X POST ${{ secrets.CLOUDFLARE_PAGES_DEPLOY_WEBHOOK }}
